### ISSUE TITLE
vega依赖了torch

### ISSUE THREAD

**Issue by ultraWeiger** [huawei-noah/vega#272]

**Comment by ultraWeiger** [comment]
详情见此

[ST][MS/modelzoo][NET][ascend][vega-noah] vega-noah 依赖torch
https://e.gitee.com/mind_spore/dashboard?issue=I5XTNW

**Comment by anzq001** [comment]
Related testcase / 关联用例 (Mandatory / 必填)
test_ms_dnet_nas_ilsvrc_ascend_check_fps_0001.py

Steps to reproduce the issue / 重现步骤 (Mandatory / 必填)
cd solution_test/cases/02network/00cv/dnet_nas/train_
pytest -s test_ms_dnet_nas_ilsvrc_ascend_check_fps_0001.py
Describe the expected behavior / 预期结果 (Mandatory / 必填)
训练成功，vega-noah不应依赖torch

Related log / screenshot / 日志 / 截图 (Mandatory / 必填)
vega-noah 依赖torch

```
ERROR:vega.core.pipeline.pipeline:Traceback (most recent call last):
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/core/pipeline/pipeline.py", line 72, in run
    PipeStepConfig.from_dict(step_cfg, skip_check=False)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/core/pipeline/conf.py", line 91, in from_dict
    cls = super(PipeStepConfig, cls).from_dict(data, skip_check)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/config_serializable.py", line 76, in from_dict
    setattr(cls, attr, class_value.from_dict(config_value, skip_check))
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/config_serializable.py", line 64, in from_dict
    _load_link_config(cls, config)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/config_serializable.py", line 134, in _load_link_config
    config_cls = _get_specific_class_config(class_type, class_name)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/config_serializable.py", line 151, in _get_specific_class_config
    specific_class = ClassFactory.get_cls(class_type, class_name)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/class_factory.py", line 192, in get_cls
    if not cls.is_exists(type_name, t_cls_name) and t_cls_name is not None:
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/class_factory.py", line 155, in is_exists
    cls._import_pkg(type_name, cls_name)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/common/class_factory.py", line 170, in _import_pkg
    __import__(pkg)
  File "/home/miniconda3/envs/ci/lib/python3.7/site-packages/vega/datasets/common/imagenet.py", line 19, in <module>
    from torchvision.datasets import ImageFolder
ModuleNotFoundError: No module named 'torchvision'
```
