### ISSUE TITLE
RuntimeError: Dataset not found or corrupted. You can use download=True to download it

### ISSUE THREAD

**Issue by pomelo-sky** [huawei-noah/vega#50]
2020-08-28 23:18:40.631 ERROR Failed to run pipeline.
Traceback (most recent call last):
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/pipeline/pipeline.py", line 52, in run
    PipeStep().do()
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/pipeline/nas_pipe_step.py", line 43, in do
    self._dispatch_trainer(res)
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/pipeline/nas_pipe_step.py", line 73, in _dispatch_trainer
    self.master.run(trainer)
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/scheduler/local_master.py", line 42, in run
    worker.train_process()
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/trainer/trainer.py", line 152, in train_process
    self.build(model=self.model, hps=self.hps, load_ckpt_flag=self.load_ckpt_flag)
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/trainer/trainer.py", line 189, in build
    mode='train', loader=train_loader)
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/core/trainer/trainer.py", line 360, in _init_dataloader
    dataset = dataset_cls(mode=mode)
  File "/usr/local/python3.7/lib/python3.7/site-packages/vega/datasets/pytorch/cifar10.py", line 41, in __init__
    transform=Compose(self.transforms.__transform__), download=self.args.download)
  File "/root/.local/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 67, in __init__
    raise RuntimeError('Dataset not found or corrupted.' +
RuntimeError: Dataset not found or corrupted. You can use download=True to download it
2020-08-28 23:18:40.631 ERROR None

I try to use the CARS algorithm to search for datasets on cifar10. The dataset path is set correctly, but the preceding error occurs. Why?

**Comment by zhangjiajin** [comment]
1.  assume that your local data set path is `/your_dataset_path/`
2.  download `cifar-10-python.tar.gz`  from <http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz>, and put it in `/your_dataset_path`.
3. run the following command:
    ```bash
    cd /your_dataset_path/
    tar zxvf cifar-10-python.tar.gz
    ```
4. set the value of `data_path` to `/your_dataset_path`

**Comment by fengChenHPC** [comment]
@pomelo-sky is your problem solved?
