### ISSUE TITLE
Inference fo auto lane

### ISSUE THREAD

**Issue by mengzhibin** [huawei-noah/vega#73]
Could you help tell how to run the inference.py to inference the auto lane model?
In the model_zoo.md, there is only model and desc file provided but inference code.
I try to use vega/model_zoo/inference.py and dont know how to set the data_type and data_path.

If you can provide document of auto lane inferencing, it will help a lot.

**Comment by zhangjiajin** [comment]
Sorry for not responding in time. We will update the version again in the near future to provide the inference script.

**Comment by wsxwsx543** [comment]
Hi, I am also working on the inference of auto_lane. I download the model and description of the model from the model zoo. (desc_25.json, model_25.pth) When I run `python vega/vega/tools/inference.py -c desc_25.json -m model_25.pth -df d -dp inputs/ -o result.pkl`, where inputs is the folder that contains some .jpg files. I get an error message: 
`Start building model.
ERROR:root:Failed to get model, model_desc=desc_25.json, msg='type'
Traceback (most recent call last):
  File "vega/vega/tools/inference.py", line 184, in <module>
    model = _get_model(args)
  File "vega/vega/tools/inference.py", line 60, in _get_model
    model = ModelZoo.get_model(args.model_desc, args.model)
  File "/root/.local/lib/python3.7/site-packages/vega/model_zoo/model_zoo.py", line 60, in get_model
    raise e
  File "/root/.local/lib/python3.7/site-packages/vega/model_zoo/model_zoo.py", line 56, in get_model
    model = NetworkDesc(model_desc).to_model()
  File "/root/.local/lib/python3.7/site-packages/vega/networks/network_desc.py", line 33, in to_model
    model = module.from_desc(self._desc)
  File "/root/.local/lib/python3.7/site-packages/vega/modules/operators/functions/serializable.py", line 200, in from_desc
    module = cls.from_desc(module_desc)
  File "/root/.local/lib/python3.7/site-packages/vega/modules/operators/functions/serializable.py", line 205, in from_desc
    module = ClassFactory.get_instance(ClassType.NETWORK, module_desc)
  File "/root/.local/lib/python3.7/site-packages/vega/common/class_factory.py", line 197, in get_instance
    t_cls_name = _params.pop('type')
KeyError: 'type'`

I am not sure how I can use the inference.py script and the model description correctly.

**Comment by Lzc06** [comment]
There is indeed this problem, we will solve it as soon as possible @wsxwsx543

**Comment by Lzc06** [comment]
Hi, @wsxwsx543. Code has been updated, please download the new model [https://github.com/huawei-noah/vega/blob/master/docs/model_zoo.md](url), use [https://github.com/huawei-noah/vega/blob/master/vega/tools/detection_inference.py](url)

**Comment by wsxwsx543** [comment]
Thanks for the update!
