### ISSUE TITLE
step_cfg = UserConfig().data.get("nas")

### ISSUE THREAD

**Issue by menglifenglin** [huawei-noah/vega#93]
When I run quant_ea.yaml, it shows that:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/lib/python3.6/site-packages/zeus/trainer_base.py", line 153, in train_process
    self._train_loop()
  File "/root/.local/lib/python3.6/site-packages/zeus/trainer_base.py", line 279, in _train_loop
    self.callbacks.before_train()
  File "/root/.local/lib/python3.6/site-packages/zeus/trainer/callbacks/callback_list.py", line 139, in before_train
    callback.before_train(logs)
  File "/root/.local/lib/python3.6/site-packages/vega/algorithms/compression/quant_ea/quant_trainer_callback.py", line 62, in before_train
    self.latency_count = calc_forward_latency(model, count_input, sess_config)
  File "/root/.local/lib/python3.6/site-packages/zeus/metrics/forward_latency.py", line 31, in calc_forward_latency
    step_cfg = UserConfig().data.get("nas")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by zhangjiajin** [comment]
This error is usually caused by incorrect format of the configuration file. As a result, the NAS node cannot be found. 

@menglifenglin
